# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.data_cloud.services.ai_tool_metrics import AiToolMetricsService
from getdx.data_cloud.services.custom_data import CustomDataService
from getdx.data_cloud.services.deployments import DeploymentsService
from getdx.data_cloud.services.incidents import IncidentsService
from getdx.data_cloud.services.pipeline_runs import PipelineRunsService
from getdx.data_cloud.services.repo_groups import RepoGroupsService

SERVICE_CLASS_BY_TAG = {
    "aiToolMetrics": AiToolMetricsService,
    "customData": CustomDataService,
    "deployments": DeploymentsService,
    "incidents": IncidentsService,
    "pipelineRuns": PipelineRunsService,
    "repoGroups": RepoGroupsService,
}

__all__ = [
    "AiToolMetricsService",
    "CustomDataService",
    "DeploymentsService",
    "IncidentsService",
    "PipelineRunsService",
    "RepoGroupsService",
]
