# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping
from getdx.http.transport import DXTransport
from getdx.types import BodyValue


class AiToolMetricsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def push(
        self,
        *,
        date: BodyValue,
        email: BodyValue,
        is_active: BodyValue,
        metrics: BodyValue | None = None,
        tool: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "date": date,
                "email": email,
                "is_active": is_active,
                "metrics": metrics,
                "tool": tool,
            }
        )
        return self._transport.request(
            "POST",
            "/aiToolMetrics.push",
            json_body=json_body,
        )

    def push_all(
        self,
        *,
        data: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "data": data,
            }
        )
        return self._transport.request(
            "POST",
            "/aiToolMetrics.pushAll",
            json_body=json_body,
        )
