# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from typing import Any

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import BodyValue, QueryScalar


class CustomDataService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def delete(
        self,
        payload: dict[str, Any],
    ) -> JSONReturn:
        return self._transport.request(
            "POST",
            "/customData.delete",
            json_body=payload,
        )

    def delete_all_by_reference(
        self,
        *,
        reference: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "reference": reference,
            }
        )
        return self._transport.request(
            "POST",
            "/customData.deleteAllByReference",
            json_body=json_body,
        )

    def get(
        self,
        *,
        reference: QueryScalar | None = None,
        key: QueryScalar | None = None,
        id: QueryScalar | None = None,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "reference": _coerce_query_value(reference),
                "key": _coerce_query_value(key),
                "id": _coerce_query_value(id),
            }
        )
        return self._transport.request(
            "GET",
            "/customData.get",
            params=params,
        )

    def get_all_by_reference(
        self,
        reference: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "reference": _coerce_query_value(reference),
            }
        )
        return self._transport.request(
            "GET",
            "/customData.getAllByReference",
            params=params,
        )

    def set(
        self,
        *,
        key: BodyValue,
        reference: BodyValue,
        timestamp: BodyValue | None = None,
        value: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "key": key,
                "reference": reference,
                "timestamp": timestamp,
                "value": value,
            }
        )
        return self._transport.request(
            "POST",
            "/customData.set",
            json_body=json_body,
        )

    def set_all(
        self,
        *,
        data: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "data": data,
            }
        )
        return self._transport.request(
            "POST",
            "/customData.setAll",
            json_body=json_body,
        )
