# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from typing import Any

from getdx.helpers import JSONReturn, _clean_mapping
from getdx.http.transport import DXTransport
from getdx.types import BodyValue


class DeploymentsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def create(
        self,
        *,
        commit_sha: BodyValue | None = None,
        deployed_at: BodyValue,
        integration_branch: BodyValue | None = None,
        merge_commit_shas: BodyValue | None = None,
        metadata: BodyValue | None = None,
        reference_id: BodyValue | None = None,
        repository: BodyValue | None = None,
        service: BodyValue,
        source_name: BodyValue | None = None,
        source_url: BodyValue | None = None,
        success: BodyValue | None = None,
    ) -> JSONReturn:
        """Create a deployment

        ``POST /deployments.create`` (``deployments_create``).
        """
        json_body = _clean_mapping(
            {
                "commit_sha": commit_sha,
                "deployed_at": deployed_at,
                "integration_branch": integration_branch,
                "merge_commit_shas": merge_commit_shas,
                "metadata": metadata,
                "reference_id": reference_id,
                "repository": repository,
                "service": service,
                "source_name": source_name,
                "source_url": source_url,
                "success": success,
            }
        )
        return self._transport.request(
            "POST",
            "/deployments.create",
            json_body=json_body,
        )

    def set_pull_services(
        self,
        payload: dict[str, Any],
    ) -> JSONReturn:
        """Associate monorepo PRs with services

        ``POST /deployments.setPullServices`` (``deployments_setPullServices``).
        """
        return self._transport.request(
            "POST",
            "/deployments.setPullServices",
            json_body=payload,
        )
