# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping
from getdx.http.transport import DXTransport
from getdx.types import BodyValue


class IncidentsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def upsert(
        self,
        *,
        metadata: BodyValue | None = None,
        name: BodyValue | None = None,
        priority: BodyValue | None = None,
        reference_id: BodyValue,
        resolved_at: BodyValue | None = None,
        services: BodyValue,
        source_url: BodyValue | None = None,
        started_at: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "metadata": metadata,
                "name": name,
                "priority": priority,
                "reference_id": reference_id,
                "resolved_at": resolved_at,
                "services": services,
                "source_url": source_url,
                "started_at": started_at,
            }
        )
        return self._transport.request(
            "POST",
            "/incidents.upsert",
            json_body=json_body,
        )
