# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping
from getdx.http.transport import DXTransport
from getdx.types import BodyValue


class PipelineRunsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def upsert(
        self,
        *,
        commit_sha: BodyValue | None = None,
        email: BodyValue | None = None,
        finished_at: BodyValue | None = None,
        github_username: BodyValue | None = None,
        gitlab_username: BodyValue | None = None,
        head_branch: BodyValue | None = None,
        pipeline_name: BodyValue,
        pipeline_source: BodyValue,
        pr_number: BodyValue | None = None,
        reference_id: BodyValue,
        repository: BodyValue | None = None,
        source_url: BodyValue | None = None,
        started_at: BodyValue,
        status: BodyValue | None = None,
    ) -> JSONReturn:
        """Create or update a pipeline run

        ``POST /pipelineRuns.upsert`` (``pipelineRuns_upsert``).
        """
        json_body = _clean_mapping(
            {
                "commit_sha": commit_sha,
                "email": email,
                "finished_at": finished_at,
                "github_username": github_username,
                "gitlab_username": gitlab_username,
                "head_branch": head_branch,
                "pipeline_name": pipeline_name,
                "pipeline_source": pipeline_source,
                "pr_number": pr_number,
                "reference_id": reference_id,
                "repository": repository,
                "source_url": source_url,
                "started_at": started_at,
                "status": status,
            }
        )
        return self._transport.request(
            "POST",
            "/pipelineRuns.upsert",
            json_body=json_body,
        )
