# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import BodyValue, QueryScalar


class RepoGroupsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def add_repos(
        self,
        *,
        id: BodyValue | None = None,
        reference_id: BodyValue | None = None,
        repos: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "id": id,
                "reference_id": reference_id,
                "repos": repos,
            }
        )
        return self._transport.request(
            "POST",
            "/repoGroups.addRepos",
            json_body=json_body,
        )

    def delete(
        self,
        *,
        id: BodyValue | None = None,
        reference_id: BodyValue | None = None,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "id": id,
                "reference_id": reference_id,
            }
        )
        return self._transport.request(
            "POST",
            "/repoGroups.delete",
            json_body=json_body,
        )

    def get(
        self,
        *,
        id: QueryScalar | None = None,
        reference_id: QueryScalar | None = None,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "id": _coerce_query_value(id),
                "reference_id": _coerce_query_value(reference_id),
            }
        )
        return self._transport.request(
            "GET",
            "/repoGroups.get",
            params=params,
        )

    def remove_repos(
        self,
        *,
        id: BodyValue | None = None,
        reference_id: BodyValue | None = None,
        repos: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "id": id,
                "reference_id": reference_id,
                "repos": repos,
            }
        )
        return self._transport.request(
            "POST",
            "/repoGroups.removeRepos",
            json_body=json_body,
        )

    def upsert(
        self,
        *,
        id: BodyValue | None = None,
        name: BodyValue,
        parent_id: BodyValue | None = None,
        reference_id: BodyValue | None = None,
        repos: BodyValue | None = None,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "id": id,
                "name": name,
                "parent_id": parent_id,
                "reference_id": reference_id,
                "repos": repos,
            }
        )
        return self._transport.request(
            "POST",
            "/repoGroups.upsert",
            json_body=json_body,
        )
