# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.web.services.entities import EntitiesService
from getdx.web.services.entity_relations import EntityRelationsService
from getdx.web.services.entity_types import EntityTypesService
from getdx.web.services.events import EventsService
from getdx.web.services.initiatives import InitiativesService
from getdx.web.services.orgfiles import OrgfilesService
from getdx.web.services.platformx import PlatformxService
from getdx.web.services.queries import QueriesService
from getdx.web.services.scorecards import ScorecardsService
from getdx.web.services.snapshots import SnapshotsService
from getdx.web.services.teams import TeamsService
from getdx.web.services.user_groups import UserGroupsService
from getdx.web.services.users import UsersService
from getdx.web.services.workflow_runs import WorkflowRunsService

SERVICE_CLASS_BY_TAG = {
    "entities": EntitiesService,
    "entityRelations": EntityRelationsService,
    "entityTypes": EntityTypesService,
    "events": EventsService,
    "initiatives": InitiativesService,
    "orgfiles": OrgfilesService,
    "platformx": PlatformxService,
    "queries": QueriesService,
    "scorecards": ScorecardsService,
    "snapshots": SnapshotsService,
    "teams": TeamsService,
    "userGroups": UserGroupsService,
    "users": UsersService,
    "workflowRuns": WorkflowRunsService,
}

__all__ = [
    "EntitiesService",
    "EntityRelationsService",
    "EntityTypesService",
    "EventsService",
    "InitiativesService",
    "OrgfilesService",
    "PlatformxService",
    "QueriesService",
    "ScorecardsService",
    "SnapshotsService",
    "TeamsService",
    "UserGroupsService",
    "UsersService",
    "WorkflowRunsService",
]
