# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import BodyValue, QueryScalar


class EntitiesService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def create(
        self,
        *,
        aliases: BodyValue | None = None,
        description: BodyValue | None = None,
        entity_type_identifier: BodyValue,
        identifier: BodyValue,
        name: BodyValue,
        properties: BodyValue | None = None,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "aliases": aliases,
                "description": description,
                "entity_type_identifier": entity_type_identifier,
                "identifier": identifier,
                "name": name,
                "properties": properties,
            }
        )
        return self._transport.request(
            "POST",
            "/entities.create",
            json_body=json_body,
        )

    def delete(
        self,
        *,
        identifier: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "identifier": identifier,
            }
        )
        return self._transport.request(
            "POST",
            "/entities.delete",
            json_body=json_body,
        )

    def info(
        self,
        identifier: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "identifier": _coerce_query_value(identifier),
            }
        )
        return self._transport.request(
            "GET",
            "/entities.info",
            params=params,
        )

    def list(
        self,
        *,
        entity_type_identifier: QueryScalar | None = None,
        cursor: QueryScalar | None = None,
        limit: QueryScalar | None = None,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "entity_type_identifier": _coerce_query_value(entity_type_identifier),
                "cursor": _coerce_query_value(cursor),
                "limit": _coerce_query_value(limit),
            }
        )
        return self._transport.request(
            "GET",
            "/entities.list",
            params=params,
        )

    def scorecards(
        self,
        identifier: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "identifier": _coerce_query_value(identifier),
            }
        )
        return self._transport.request(
            "GET",
            "/entities.scorecards",
            params=params,
        )

    def tasks(
        self,
        identifier: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "identifier": _coerce_query_value(identifier),
            }
        )
        return self._transport.request(
            "GET",
            "/entities.tasks",
            params=params,
        )

    def update(
        self,
        *,
        aliases: BodyValue | None = None,
        description: BodyValue | None = None,
        identifier: BodyValue,
        name: BodyValue | None = None,
        properties: BodyValue | None = None,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "aliases": aliases,
                "description": description,
                "identifier": identifier,
                "name": name,
                "properties": properties,
            }
        )
        return self._transport.request(
            "POST",
            "/entities.update",
            json_body=json_body,
        )

    def upsert(
        self,
        *,
        aliases: BodyValue | None = None,
        description: BodyValue | None = None,
        entity_type_identifier: BodyValue,
        identifier: BodyValue,
        name: BodyValue | None = None,
        properties: BodyValue | None = None,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "aliases": aliases,
                "description": description,
                "entity_type_identifier": entity_type_identifier,
                "identifier": identifier,
                "name": name,
                "properties": properties,
            }
        )
        return self._transport.request(
            "POST",
            "/entities.upsert",
            json_body=json_body,
        )
