# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import BodyValue, QueryScalar


class EntitiesService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def create(
        self,
        *,
        aliases: BodyValue | None = None,
        description: BodyValue | None = None,
        entity_type_identifier: BodyValue,
        identifier: BodyValue,
        name: BodyValue,
        properties: BodyValue | None = None,
    ) -> JSONReturn:
        """Create entity

        ``POST /catalog.entities.create`` (``entities_create``).
        """
        json_body = _clean_mapping(
            {
                "aliases": aliases,
                "description": description,
                "entity_type_identifier": entity_type_identifier,
                "identifier": identifier,
                "name": name,
                "properties": properties,
            }
        )
        return self._transport.request(
            "POST",
            "/catalog.entities.create",
            json_body=json_body,
        )

    def delete(
        self,
        identifier: QueryScalar,
    ) -> JSONReturn:
        """Delete entity

        ``POST /catalog.entities.delete`` (``entities_delete``).
        """
        params = _clean_mapping(
            {
                "identifier": _coerce_query_value(identifier),
            }
        )
        return self._transport.request(
            "POST",
            "/catalog.entities.delete",
            params=params,
        )

    def info(
        self,
        identifier: QueryScalar,
    ) -> JSONReturn:
        """Get entity info

        ``GET /catalog.entities.info`` (``entities_info``).
        """
        params = _clean_mapping(
            {
                "identifier": _coerce_query_value(identifier),
            }
        )
        return self._transport.request(
            "GET",
            "/catalog.entities.info",
            params=params,
        )

    def list(
        self,
        *,
        type: QueryScalar | None = None,
        cursor: QueryScalar | None = None,
        limit: QueryScalar | None = None,
        search_term: QueryScalar | None = None,
    ) -> JSONReturn:
        """List entities

        ``GET /catalog.entities.list`` (``entities_list``).
        """
        params = _clean_mapping(
            {
                "type": _coerce_query_value(type),
                "cursor": _coerce_query_value(cursor),
                "limit": _coerce_query_value(limit),
                "search_term": _coerce_query_value(search_term),
            }
        )
        return self._transport.request(
            "GET",
            "/catalog.entities.list",
            params=params,
        )

    def scorecards(
        self,
        identifier: QueryScalar,
    ) -> JSONReturn:
        """Get entity scorecards

        ``GET /catalog.entities.scorecards`` (``entities_scorecards``).
        """
        params = _clean_mapping(
            {
                "identifier": _coerce_query_value(identifier),
            }
        )
        return self._transport.request(
            "GET",
            "/catalog.entities.scorecards",
            params=params,
        )

    def tasks(
        self,
        identifier: QueryScalar,
    ) -> JSONReturn:
        """List entity tasks

        ``GET /catalog.entities.tasks`` (``entities_tasks``).
        """
        params = _clean_mapping(
            {
                "identifier": _coerce_query_value(identifier),
            }
        )
        return self._transport.request(
            "GET",
            "/catalog.entities.tasks",
            params=params,
        )

    def update(
        self,
        *,
        aliases: BodyValue | None = None,
        description: BodyValue | None = None,
        identifier: BodyValue,
        name: BodyValue | None = None,
        owner_team_ids: BodyValue | None = None,
        owner_user_emails: BodyValue | None = None,
        owner_user_ids: BodyValue | None = None,
        properties: BodyValue | None = None,
    ) -> JSONReturn:
        """Update entity

        ``POST /catalog.entities.update`` (``entities_update``).
        """
        json_body = _clean_mapping(
            {
                "aliases": aliases,
                "description": description,
                "identifier": identifier,
                "name": name,
                "owner_team_ids": owner_team_ids,
                "owner_user_emails": owner_user_emails,
                "owner_user_ids": owner_user_ids,
                "properties": properties,
            }
        )
        return self._transport.request(
            "POST",
            "/catalog.entities.update",
            json_body=json_body,
        )

    def upsert(
        self,
        *,
        aliases: BodyValue | None = None,
        description: BodyValue | None = None,
        domain: BodyValue | None = None,
        identifier: BodyValue,
        name: BodyValue | None = None,
        owner_team_ids: BodyValue | None = None,
        owner_user_emails: BodyValue | None = None,
        owner_user_ids: BodyValue | None = None,
        properties: BodyValue | None = None,
        type: BodyValue,
    ) -> JSONReturn:
        """Upsert entity

        ``POST /catalog.entities.upsert`` (``entities_upsert``).
        """
        json_body = _clean_mapping(
            {
                "aliases": aliases,
                "description": description,
                "domain": domain,
                "identifier": identifier,
                "name": name,
                "owner_team_ids": owner_team_ids,
                "owner_user_emails": owner_user_emails,
                "owner_user_ids": owner_user_ids,
                "properties": properties,
                "type": type,
            }
        )
        return self._transport.request(
            "POST",
            "/catalog.entities.upsert",
            json_body=json_body,
        )
