# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import BodyValue, QueryScalar


class EntityTypesService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def create(
        self,
        *,
        aliases: BodyValue | None = None,
        description: BodyValue | None = None,
        identifier: BodyValue,
        name: BodyValue,
        ordering: BodyValue | None = None,
        properties: BodyValue | None = None,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "aliases": aliases,
                "description": description,
                "identifier": identifier,
                "name": name,
                "ordering": ordering,
                "properties": properties,
            }
        )
        return self._transport.request(
            "POST",
            "/entityTypes.create",
            json_body=json_body,
        )

    def delete(
        self,
        *,
        identifier: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "identifier": identifier,
            }
        )
        return self._transport.request(
            "POST",
            "/entityTypes.delete",
            json_body=json_body,
        )

    def info(
        self,
        identifier: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "identifier": _coerce_query_value(identifier),
            }
        )
        return self._transport.request(
            "GET",
            "/entityTypes.info",
            params=params,
        )

    def list(
        self,
        *,
        cursor: QueryScalar | None = None,
        limit: QueryScalar | None = None,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "cursor": _coerce_query_value(cursor),
                "limit": _coerce_query_value(limit),
            }
        )
        return self._transport.request(
            "GET",
            "/entityTypes.list",
            params=params,
        )

    def update(
        self,
        *,
        aliases: BodyValue | None = None,
        description: BodyValue | None = None,
        identifier: BodyValue,
        name: BodyValue | None = None,
        ordering: BodyValue | None = None,
        properties: BodyValue | None = None,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "aliases": aliases,
                "description": description,
                "identifier": identifier,
                "name": name,
                "ordering": ordering,
                "properties": properties,
            }
        )
        return self._transport.request(
            "POST",
            "/entityTypes.update",
            json_body=json_body,
        )
