# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import QueryScalar


class EntityRelationsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def list(
        self,
        *,
        entity_identifier: QueryScalar | None = None,
        relation_type: QueryScalar | None = None,
        cursor: QueryScalar | None = None,
        limit: QueryScalar | None = None,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "entity_identifier": _coerce_query_value(entity_identifier),
                "relation_type": _coerce_query_value(relation_type),
                "cursor": _coerce_query_value(cursor),
                "limit": _coerce_query_value(limit),
            }
        )
        return self._transport.request(
            "GET",
            "/entityRelations.list",
            params=params,
        )
