# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping
from getdx.http.transport import DXTransport
from getdx.types import BodyValue


class EventsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def track(
        self,
        *,
        event_type: BodyValue,
        properties: BodyValue | None = None,
        timestamp: BodyValue,
    ) -> JSONReturn:
        """Track event

        ``POST /events.track`` (``events_track``).
        """
        json_body = _clean_mapping(
            {
                "event_type": event_type,
                "properties": properties,
                "timestamp": timestamp,
            }
        )
        return self._transport.request(
            "POST",
            "/events.track",
            json_body=json_body,
        )
