# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import QueryScalar


class InitiativesService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def info(
        self,
        id: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "id": _coerce_query_value(id),
            }
        )
        return self._transport.request(
            "GET",
            "/initiatives.info",
            params=params,
        )

    def list(
        self,
        *,
        cursor: QueryScalar | None = None,
        limit: QueryScalar | None = None,
        published: QueryScalar | None = None,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "cursor": _coerce_query_value(cursor),
                "limit": _coerce_query_value(limit),
                "published": _coerce_query_value(published),
            }
        )
        return self._transport.request(
            "GET",
            "/initiatives.list",
            params=params,
        )

    def progress_report(
        self,
        id: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "id": _coerce_query_value(id),
            }
        )
        return self._transport.request(
            "GET",
            "/initiatives.progressReport",
            params=params,
        )
