# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import BodyValue, QueryScalar


class OrgfilesService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def list(
        self,
        *,
        cursor: QueryScalar | None = None,
        limit: QueryScalar | None = None,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "cursor": _coerce_query_value(cursor),
                "limit": _coerce_query_value(limit),
            }
        )
        return self._transport.request(
            "GET",
            "/orgfiles.list",
            params=params,
        )

    def team_hierarchy_get(
        self,
        id: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "id": _coerce_query_value(id),
            }
        )
        return self._transport.request(
            "GET",
            "/orgfiles.teamHierarchy.get",
            params=params,
        )

    def team_hierarchy_preview(
        self,
        *,
        file_content: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "file_content": file_content,
            }
        )
        return self._transport.request(
            "POST",
            "/orgfiles.teamHierarchy.preview",
            json_body=json_body,
        )

    def team_hierarchy_process(
        self,
        *,
        file_id: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "file_id": file_id,
            }
        )
        return self._transport.request(
            "POST",
            "/orgfiles.teamHierarchy.process",
            json_body=json_body,
        )

    def upload(
        self,
        *,
        file: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "file": file,
            }
        )
        return self._transport.request(
            "POST",
            "/orgfiles.upload",
            json_body=json_body,
        )
