# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import BodyValue, QueryScalar


class PlatformxService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def projects_create(
        self,
        *,
        description: BodyValue | None = None,
        name: BodyValue,
    ) -> JSONReturn:
        """Create PlatformX project

        ``POST /platformx.projects.create`` (``platformx_projects_create``).
        """
        json_body = _clean_mapping(
            {
                "description": description,
                "name": name,
            }
        )
        return self._transport.request(
            "POST",
            "/platformx.projects.create",
            json_body=json_body,
        )

    def projects_list(
        self,
        *,
        cursor: QueryScalar | None = None,
        limit: QueryScalar | None = None,
    ) -> JSONReturn:
        """List PlatformX projects

        ``GET /platformx.projects.list`` (``platformx_projects_list``).
        """
        params = _clean_mapping(
            {
                "cursor": _coerce_query_value(cursor),
                "limit": _coerce_query_value(limit),
            }
        )
        return self._transport.request(
            "GET",
            "/platformx.projects.list",
            params=params,
        )
