# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import QueryScalar


class QueriesService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def datafeed(
        self,
        query: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "query": _coerce_query_value(query),
            }
        )
        return self._transport.request(
            "GET",
            "/queries.datafeed",
            params=params,
        )
