# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import BodyValue, QueryScalar


class ScorecardsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def create(
        self,
        *,
        description: BodyValue | None = None,
        entity_type_identifiers: BodyValue | None = None,
        name: BodyValue,
    ) -> JSONReturn:
        """Create scorecard

        ``POST /scorecards.create`` (``scorecards_create``).
        """
        json_body = _clean_mapping(
            {
                "description": description,
                "entity_type_identifiers": entity_type_identifiers,
                "name": name,
            }
        )
        return self._transport.request(
            "POST",
            "/scorecards.create",
            json_body=json_body,
        )

    def delete(
        self,
        *,
        id: BodyValue,
    ) -> JSONReturn:
        """Delete scorecard

        ``POST /scorecards.delete`` (``scorecards_delete``).
        """
        json_body = _clean_mapping(
            {
                "id": id,
            }
        )
        return self._transport.request(
            "POST",
            "/scorecards.delete",
            json_body=json_body,
        )

    def info(
        self,
        id: QueryScalar,
    ) -> JSONReturn:
        """Get scorecard info

        ``GET /scorecards.info`` (``scorecards_info``).
        """
        params = _clean_mapping(
            {
                "id": _coerce_query_value(id),
            }
        )
        return self._transport.request(
            "GET",
            "/scorecards.info",
            params=params,
        )

    def list(
        self,
        *,
        cursor: QueryScalar | None = None,
        limit: QueryScalar | None = None,
    ) -> JSONReturn:
        """List scorecards

        ``GET /scorecards.list`` (``scorecards_list``).
        """
        params = _clean_mapping(
            {
                "cursor": _coerce_query_value(cursor),
                "limit": _coerce_query_value(limit),
            }
        )
        return self._transport.request(
            "GET",
            "/scorecards.list",
            params=params,
        )

    def update(
        self,
        *,
        description: BodyValue | None = None,
        id: BodyValue,
        name: BodyValue | None = None,
    ) -> JSONReturn:
        """Update scorecard

        ``POST /scorecards.update`` (``scorecards_update``).
        """
        json_body = _clean_mapping(
            {
                "description": description,
                "id": id,
                "name": name,
            }
        )
        return self._transport.request(
            "POST",
            "/scorecards.update",
            json_body=json_body,
        )
