# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import QueryScalar


class SnapshotsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def comments_list(
        self,
        snapshot_id: QueryScalar,
    ) -> JSONReturn:
        """List snapshot comments

        ``GET /snapshots.comments.list`` (``snapshots_comments_list``).
        """
        params = _clean_mapping(
            {
                "snapshot_id": _coerce_query_value(snapshot_id),
            }
        )
        return self._transport.request(
            "GET",
            "/snapshots.comments.list",
            params=params,
        )

    def get_file(
        self,
        snapshot_id: QueryScalar,
        file_path: QueryScalar,
    ) -> JSONReturn:
        """Get snapshot file

        ``GET /snapshots.getFile`` (``snapshots_getFile``).
        """
        params = _clean_mapping(
            {
                "snapshot_id": _coerce_query_value(snapshot_id),
                "file_path": _coerce_query_value(file_path),
            }
        )
        return self._transport.request(
            "GET",
            "/snapshots.getFile",
            params=params,
        )

    def info(
        self,
        id: QueryScalar,
    ) -> JSONReturn:
        """Get snapshot info

        ``GET /snapshots.info`` (``snapshots_info``).
        """
        params = _clean_mapping(
            {
                "id": _coerce_query_value(id),
            }
        )
        return self._transport.request(
            "GET",
            "/snapshots.info",
            params=params,
        )

    def list(
        self,
        *,
        cursor: QueryScalar | None = None,
        limit: QueryScalar | None = None,
    ) -> JSONReturn:
        """List snapshots

        ``GET /snapshots.list`` (``snapshots_list``).
        """
        params = _clean_mapping(
            {
                "cursor": _coerce_query_value(cursor),
                "limit": _coerce_query_value(limit),
            }
        )
        return self._transport.request(
            "GET",
            "/snapshots.list",
            params=params,
        )
