# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import QueryScalar


class TeamsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def audit_trail(
        self,
        team_id: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "team_id": _coerce_query_value(team_id),
            }
        )
        return self._transport.request(
            "GET",
            "/teams.auditTrail",
            params=params,
        )

    def find_by_members(
        self,
        team_emails: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "team_emails": _coerce_query_value(team_emails),
            }
        )
        return self._transport.request(
            "GET",
            "/teams.findByMembers",
            params=params,
        )

    def info(
        self,
        *,
        team_id: QueryScalar | None = None,
        reference_id: QueryScalar | None = None,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "team_id": _coerce_query_value(team_id),
                "reference_id": _coerce_query_value(reference_id),
            }
        )
        return self._transport.request(
            "GET",
            "/teams.info",
            params=params,
        )

    def list(
        self,
        *,
        cursor: QueryScalar | None = None,
        limit: QueryScalar | None = None,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "cursor": _coerce_query_value(cursor),
                "limit": _coerce_query_value(limit),
            }
        )
        return self._transport.request(
            "GET",
            "/teams.list",
            params=params,
        )
