# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import BodyValue, QueryScalar


class UserGroupsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def create(
        self,
        *,
        description: BodyValue | None = None,
        name: BodyValue,
        user_emails: BodyValue | None = None,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "description": description,
                "name": name,
                "user_emails": user_emails,
            }
        )
        return self._transport.request(
            "POST",
            "/userGroups.create",
            json_body=json_body,
        )

    def delete(
        self,
        *,
        id: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "id": id,
            }
        )
        return self._transport.request(
            "POST",
            "/userGroups.delete",
            json_body=json_body,
        )

    def get(
        self,
        id: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "id": _coerce_query_value(id),
            }
        )
        return self._transport.request(
            "GET",
            "/userGroups.get",
            params=params,
        )

    def list(
        self,
        *,
        cursor: QueryScalar | None = None,
        limit: QueryScalar | None = None,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "cursor": _coerce_query_value(cursor),
                "limit": _coerce_query_value(limit),
            }
        )
        return self._transport.request(
            "GET",
            "/userGroups.list",
            params=params,
        )

    def update(
        self,
        *,
        description: BodyValue | None = None,
        id: BodyValue,
        name: BodyValue | None = None,
        user_emails: BodyValue | None = None,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "description": description,
                "id": id,
                "name": name,
                "user_emails": user_emails,
            }
        )
        return self._transport.request(
            "POST",
            "/userGroups.update",
            json_body=json_body,
        )
