# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import BodyValue, QueryScalar


class UsersService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def attributes_update(
        self,
        *,
        attributes: BodyValue | None = None,
        email: BodyValue,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "attributes": attributes,
                "email": email,
            }
        )
        return self._transport.request(
            "POST",
            "/users.attributes.update",
            json_body=json_body,
        )

    def find_by_github_username(
        self,
        username: QueryScalar,
    ) -> JSONReturn:
        params = _clean_mapping(
            {
                "username": _coerce_query_value(username),
            }
        )
        return self._transport.request(
            "GET",
            "/users.findByGithubUsername",
            params=params,
        )

    def update(
        self,
        *,
        email: BodyValue,
        name: BodyValue | None = None,
        properties: BodyValue | None = None,
    ) -> JSONReturn:
        json_body = _clean_mapping(
            {
                "email": email,
                "name": name,
                "properties": properties,
            }
        )
        return self._transport.request(
            "POST",
            "/users.update",
            json_body=json_body,
        )
