# This file is auto-generated by scripts/generate_from_openapi.py

from __future__ import annotations

from getdx.helpers import JSONReturn, _clean_mapping, _coerce_query_value
from getdx.http.transport import DXTransport
from getdx.types import BodyValue, QueryScalar


class WorkflowRunsService:
    def __init__(self, transport: DXTransport) -> None:
        self._transport = transport

    def add_link(
        self,
        *,
        run_id: BodyValue,
        title: BodyValue | None = None,
        url: BodyValue,
    ) -> JSONReturn:
        """Add workflow run link

        ``POST /workflowRuns.addLink`` (``workflowRuns_addLink``).
        """
        json_body = _clean_mapping(
            {
                "run_id": run_id,
                "title": title,
                "url": url,
            }
        )
        return self._transport.request(
            "POST",
            "/workflowRuns.addLink",
            json_body=json_body,
        )

    def change_status(
        self,
        *,
        run_id: BodyValue,
        status: BodyValue,
    ) -> JSONReturn:
        """Change workflow run status

        ``POST /workflowRuns.changeStatus`` (``workflowRuns_changeStatus``).
        """
        json_body = _clean_mapping(
            {
                "run_id": run_id,
                "status": status,
            }
        )
        return self._transport.request(
            "POST",
            "/workflowRuns.changeStatus",
            json_body=json_body,
        )

    def info(
        self,
        run_id: QueryScalar,
    ) -> JSONReturn:
        """Get workflow run info

        ``GET /workflowRuns.info`` (``workflowRuns_info``).
        """
        params = _clean_mapping(
            {
                "run_id": _coerce_query_value(run_id),
            }
        )
        return self._transport.request(
            "GET",
            "/workflowRuns.info",
            params=params,
        )

    def post_message(
        self,
        *,
        message: BodyValue,
        run_id: BodyValue,
    ) -> JSONReturn:
        """Post workflow run message

        ``POST /workflowRuns.postMessage`` (``workflowRuns_postMessage``).
        """
        json_body = _clean_mapping(
            {
                "message": message,
                "run_id": run_id,
            }
        )
        return self._transport.request(
            "POST",
            "/workflowRuns.postMessage",
            json_body=json_body,
        )

    def trigger(
        self,
        *,
        parameters: BodyValue | None = None,
        workflow_id: BodyValue,
    ) -> JSONReturn:
        """Trigger workflow run

        ``POST /workflowRuns.trigger`` (``workflowRuns_trigger``).
        """
        json_body = _clean_mapping(
            {
                "parameters": parameters,
                "workflow_id": workflow_id,
            }
        )
        return self._transport.request(
            "POST",
            "/workflowRuns.trigger",
            json_body=json_body,
        )
